source 'https://rubygems.org'

gem 'json'
gem 'jekyll'
#gem 'pygments.rb'
gem 'jekyll-paginate'
#gem 'redcarpet'
gem 'kramdown'
gem 'rouge'
gem 'jekyll-watch'
gem 'wdm', '>= 0.1.0'
gem 'github-pages'
